# Generated by Django 5.0.1 on 2024-01-31 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_organization_rename_name_book_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='title',
            new_name='name',
        ),
    ]
